scipy/oldest-supported-numpy

README.rst
setup.cfg

Change URLs to point to the scipy org, now that the repo lives here.

MAINT: point URLs to the scipy org

---

README.rst
setup.cfg

The term "supported" is ambiguous. Answer "supported by *who*" in README
and package description, and explain the reason why this metapackage
exists.

DOC: clarify what 'supported' means

---

.github/workflows/main.yml
setup.cfg

Since there isn't yet a version of Numpy with wheels for Python 3.9 (and certainly not 3.10) I thought it would probably make sense in general to use an unpinned (and therefore latest available) version of Numpy as opposed to using the one for Python 3.8.

Add unpinned Numpy for unsupported/future Python versions

---

.github/workflows/main.yml
setup.cfg

**DO NOT MERGE!**
This is in preparation of Python 3.9 being released as discussed in #8. We shouldn't merge until it is confirmed that 1.19.3 is the first version of Numpy with wheels for Python 3.9.

Avoid duplication for recent Python versions and add Python 3.9

---

setup.cfg

Downloads for:
- https://pypi.org/project/numpy/1.18.5/#files (no aarch64)
- https://pypi.org/project/numpy/1.19.0/#files (aarch64)
xref:
- https://github.com/scikit-learn/scikit-learn/pull/18782#issuecomment-723464240
- https://github.com/scikit-learn/scikit-learn/pull/18761 see: https://github.com/scikit-learn/scikit-learn/pull/18761/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

Add constraints for aarch64: numpy==1.19.0 for Python<=3.8

---

setup.cfg

Binary wheels for pypy3.7 are now available since 1.20 was released

Update for pypy3.7 wheels

---

setup.cfg

arm64 requires 1.20.0 or above

---

setup.cfg

This is the first NumPy version with universal2 wheels, and 1.21.0
was just released so we can do the version bump.
This is a follow-up to gh-19 and gh-20 (Cc @kbourgoin)

Update macOS ARM64 requirement to 1.21.0

---

.github/workflows/main.yml
setup.cfg

There are now Linux `x86_64` and aarch64 wheels up for 1.21.2,
and the sdist should work for other platforms (wheels will follow,
some infra issues to resolve first - see
https://github.com/MacPython/numpy-wheels/issues/116)

Add 1.21.2 requirement for Python 3.10

---

setup.cfg

The conflicting requirements fail immediately when copying these specifications directly in a requirements file.
However, when processed through `pip install oldest-support-numpy`, pip confusingly installs the two Numpy versions one after the other... (and keeps the wrong one :-/)

Remove conflicting requirements for s390x

---

setup.cfg
tests/test_dependencies.py

The conflicting requirements fail immediately when install oldest-supported-numpy with pypy aarch64.
```
oldest-supported-numpy 0.14 depends on numpy==1.19.2; python_version == "3.7" and platform_machine == "aarch64"
oldest-supported-numpy 0.14 depends on numpy==1.20.0; python_version == "3.7" and platform_python_implementation == "PyPy"
```
We can use below cmd to make sure there are only **cpython** support for aarch64, but **pypy** not supported yet.
`curl https://pypi.org/pypi/numpy/json | jq | grep filename | grep whl | grep aarch64`
<details>
<summary>Results</summary>
```
"filename": "numpy-1.19.0-cp36-cp36m-manylinux2014_aarch64.whl",
"filename": "numpy-1.19.0-cp37-cp37m-manylinux2014_aarch64.whl",
"filename": "numpy-1.19.0-cp38-cp38-manylinux2014_aarch64.whl",
"filename": …
```

Resolve conflict with pypy aarch64

---

setup.cfg
tests/test_dependencies.py

If you look at the versions of numpy: [1.21.4](https://pypi.org/project/numpy/1.21.4/#files), [1.21.5](https://pypi.org/project/numpy/1.21.5/#files), [1.22.0](https://pypi.org/project/numpy/1.22.0/#files), [1.22.1](https://pypi.org/project/numpy/1.22.1/#files), [1.22.2](https://pypi.org/project/numpy/1.22.2/#files), [1.22.3](https://pypi.org/project/numpy/1.22.3/#files), Windows x86 wheels for python 3.10 was only added from 1.22.3. See https://github.com/numpy/numpy/issues/20320#issuecomment-1064284778= for more info on that.

x86 windows wheels were only added from 1.22.3

---

.github/workflows/main.yml
setup.cfg
tests/test_dependencies.py

This add individual runtime test to see that numpy is properly installed on ubuntu/windows/mac for cpython. It tests 3.6-3.10 (3.5 was too old to test...).
I'm adding it because https://github.com/scipy/oldest-supported-numpy/pull/44 was incorrect. `platform_machine` tests the machine it runs on, not the installed python bitness. This is commented on here: https://github.com/pypa/pipenv/issues/2397#issuecomment-399416741= that this was a mistake when originally specified.
The tests I added show this failure.
Where it leaves us is that there's no way to differentiate 32 bit from 64 bit. So that leaves the original issue of that PR and #45. I'm not sure if we should just blindly increase the minimum numpy version for both arches for Windows to `1.22.3`?

Add individiual runtime tests

---

setup.cfg

Would allow installation of pandas and related libraries to work successfully on Mac M1 Pro processors using Python 3.7. 
Unlikely combination, but we unfortunately need it for the time being.
Tested using python 3.7.13 and pandas 1.3.5, wheels built successfully.

Add py37 support for arm64

---

.github/workflows/main.yml
setup.cfg

Closes #45. Not sure if there's any extra testing that's needed, but I think this should resolve the issue.

fix: support Windows 32-bit cross-compiles

---

setup.cfg

Numpy is publishing 3.8 wheels since [1.22.0](https://github.com/numpy/numpy/releases/tag/v1.22.0)

add pypy38

---

setup.cfg

Numpy 1.22.0 had a regression that prevented building packages against the Python limited C API, that was fixed in Numpy 1.22.2. See numpy/numpy#20818.
This is causes build failures for my Astropy affiliated package (https://git.ligo.org/lscsoft/ligo.skymap), which like many Astropy affiliated package, depends on oldest-supported-numpy.

Use Numpy 1.22.2 instead of 1.22.0

---

setup.cfg

From discussion [here](https://github.com/scipy/scipy/pull/16287), CC @rgommers 
We can replace the direct negation of `platform_machine=='arm64' and platform_system=='Darwin'` above with only `platform_machine not in ('arm64')` because there are no machines that satisfy arm64+non-Darwin.

simplify condition for platform_machine

---

setup.cfg

NumPy 1.21.0 doesn't have `universal2` wheels, and either way those are irrelevant/useless: we need `arm64` wheels.

Edit code comment: universal2 -> arm64 wheels on macOS

---

setup.cfg
tests/test_dependencies.py

I am adding the oldest Numpy version for IBM i , which include our fixes for IBM i platform. Please help to review. thanks.
@rgommers need your help again. thx.

support the IBMi platform

---

setup.py

This fixes a bug with GitHub's dependency graph, which is [currently empty](https://github.com/scipy/oldest-supported-numpy/network/dependents).
More on the issue here: https://github.com/orgs/community/discussions/6456

Fix GitHub dependency graph

---

setup.cfg

Got bit by this in Matplotlib CI where it was selecting 1.19.3 for pypy39.

MNT: add pins for pypy39

---

setup.cfg
tests/test_dependencies.py

- NumPy 1.26.0 adds support for Python 3.12.
- NumPy 1.25.0 has Python 3.9 compatible wheels for PyPy
Looks like the PyPy addition is also taken care of in #78, so that might be a conflict.

Update after NumPy 1.26.0 release

---

setup.cfg

numpy 1.26 before 1.26.2 enforced the presence of a blas library when building from source, e.g. on i686 ( https://github.com/numpy/numpy/issues/24703 )
I have encountered this at: https://github.com/bxlab/bx-python/actions/runs/7180855870/job/19554009744#step:6:1827

Bump default numpy on Python3.12 to 1.26.2

---

setup.cfg

proposed fix for #80 
as mentioned in https://github.com/scipy/oldest-supported-numpy/issues/80#issuecomment-1860363010 I do not know all the implication of updating a `patch` version so please feel free to close this PR if it's not possible to update numpy to `1.19.3`

update to 1.19.3 for python3.8 in aarch64 to limit cython<3.0

---

README.rst

DOC: deprecate this package
